export const spanishTypes = {
  normal: "normal",
  fighting: "luchador",
  flying: "volador",
  poison: "veneno",
  ground: "tierra",
  rock: "roca",
  bug: "insecto",
  ghost: "fantasma",
  steel: "acero",
  fire: "fuego",
  water: "agua",
  grass: "planta",
  electric: "electrico",
  psychic: "psíquico",
  ice: "hielo",
  dragon: "dragon",
  dark: "oscuridad",
  fairy: "hada",
  unknown: "desconocido",
  shadow: "sombra",
};
